version: '3'

services:

  azuredeployment:
    container_name: AzureDeploy
    build:
      context: ./azure/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./azure:/storage/
    env_file:
      - azure/.env

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  rabbitmq:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: airflow
      RABBITMQ_DEFAULT_PASS: airflow

  webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=amqp://airflow:airflow@rabbitmq
    volumes:
      - ./airflow/dags:/opt/airflow/dags

    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
          
  scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=amqp://airflow:airflow@rabbitmq
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  worker:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=amqp://airflow:airflow@rabbitmq
    volumes:
      - ./airflow/dags:/opt/airflow/dags
